FROM openjdk:17-jdk-slim

RUN apt-get update && apt-get install -y maven

WORKDIR /app

COPY pom.xml .
COPY .mvn/ .mvn
COPY mvnw .
COPY mvnw.cmd .

RUN mvn dependency:go-offline

COPY src ./src

RUN mvn clean package -DskipTests

EXPOSE 8080

ARG SPRING_DATASOURCE_DB
ARG SPRING_DATASOURCE_HOST
ARG SPRING_DATASOURCE_PORT
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG SPRING_FLYWAY_PROFILE
ARG JWT_SECRET_KEY

ENV SPRING_DATASOURCE_DB=${SPRING_DATASOURCE_DB}
ENV SPRING_DATASOURCE_HOST=${SPRING_DATASOURCE_HOST}
ENV SPRING_DATASOURCE_PORT=${SPRING_DATASOURCE_PORT}
ENV SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
ENV SPRING_FLYWAY_PROFILE=${SPRING_FLYWAY_PROFILE}
ENV JWT_SECRET_KEY=${JWT_SECRET_KEY}

CMD ["java", "-jar", "target/ika-api-0.0.1.jar"]
