INSERT INTO labels (id, description) VALUES
(UUID_GENERATE_V4(), 'Tomou o medicamento'),
(UUID_GENERATE_V4(), 'Não tomou o medicamento'),
(UUID_GENERATE_V4(), 'Tomou com água'),
(UUID_GENERATE_V4(), 'Tomou sem água'),
(UUID_GENERATE_V4(), 'Tomou em pé'),
(UUID_GENERATE_V4(), 'Tomou sentado'),
(UUID_GENERATE_V4(), 'Tomou deitado'),
(UUID_GENERATE_V4(), 'Tomou mais de um medicamento'),
(UUID_GENERATE_V4(), 'Tomou a dose completa'),
(UUID_GENERATE_V4(), 'Tomou apenas uma parte da dose'),
(UUID_GENERATE_V4(), 'Tomou fora do horário prescrito'),
(UUID_GENERATE_V4(), 'Tomou no horário prescrito'),
(UUID_GENERATE_V4(), 'Engoliu o medicamento'),
(UUID_GENERATE_V4(), 'Cuspiu o medicamento'),
(UUID_GENERATE_V4(), 'Aparentemente distraído durante a ingestão'),
(UUID_GENERATE_V4(), 'Aparentemente com dificuldade para engolir'),
(UUID_GENERATE_V4(), 'Tomou com supervisão'),
(UUID_GENERATE_V4(), 'Tomou sem supervisão');
